//
// Created by josea4718 on 3/2/21.
//

#ifndef TAREA_EXTRACLASE_1_DATOS_II_COLLECTOR_H
#define TAREA_EXTRACLASE_1_DATOS_II_COLLECTOR_H


class Collector {

};


#endif //TAREA_EXTRACLASE_1_DATOS_II_COLLECTOR_H
